name: sphinx
channels:
  - conda-forge
dependencies:
  - python
  - sphinx
  - sphinx-intl
  - sphinx-comments
  - sphinx-copybutton
  - sphinx-design
  - sphinx-book-theme 0.2.*
  - ablog
  - myst-parser
